data:
  image: busybox
  volumes:
    - /usr/share/elasticsearch/data
    - /var/lib/postgresql/data
    - /usr/share/nginx/html/media
  command: tail -f /dev/null
  restart: always

elasticsearch:
  image: elasticsearch
  volumes_from:
    - data
  restart: always

postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: something
  volumes_from:
    - data
  restart: always

restyaboard:
  build: .
  links:
    - elasticsearch:elasticsearch
    - postgres:postgres
  ports:
    - 80:80
  volumes_from:
    - data
  restart: always
